{% set name = "pynomaly" %}
{% set version = "0.3.3" %}
{% set sha256 = "8bf89d904eccccde581fc27d90295bb4a7e9de6cc3a2dd726fdd79df8678e0bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyNomaly-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-utils >=2.3.0
    - numpy
  run_constrained:
    - numba >=0.45.1

test:
  requires:
    - pip
    - numba
    - numpy <1.22
  imports:
    - PyNomaly
    - PyNomaly.loop
  commands:
    - pip check

about:
  home: https://github.com/vc1492a/PyNomaly
  summary: 'A Python 3 implementation of LoOP: Local Outlier Probabilities.'
  description: |
    PyNomaly is a Python 3 implementation of LoOP (Local Outlier Probabilities).
    LoOP is a local density based outlier detection method by Kriegel, Kröger,
    Schubert, and Zimek which provides outlier scores in the range of [0,1] that
    are directly interpretable as the probability of a sample being an outlier.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  doc_url: https://github.com/vc1492a/PyNomaly/blob/main/readme.md
  doc_source_url: https://github.com/vc1492a/PyNomaly/blob/main/readme.md
  dev_url: https://github.com/vc1492a/PyNomaly

extra:
  recipe-maintainers:
    - thewchan
